apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
  labels:
    app: my-app
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      env:
        # Inject DB_PASSWORD from Secret my-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: DB_PASSWORD
        # Inject API_KEY from Secret my-secret
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: API_KEY
