apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  # Total capacity of this PersistentVolume
  capacity:
    storage: 1Gi
  # ReadWriteOnce — can be mounted by one node at a time
  accessModes:
    - ReadWriteOnce
  # Retain — data is kept even after the PVC is deleted
  persistentVolumeReclaimPolicy: Retain
  # hostPath used for minikube demo
  # In production use AWS EBS, GCP PD, Azure Disk etc.
  hostPath:
    path: /tmp/my-pv-data
