apiVersion: v1
kind: Pod
metadata:
  name: my-sa-pod
  labels:
    app: my-app
spec:
  # Use our custom ServiceAccount instead of the default one
  serviceAccountName: my-service-account
  # Token will be automatically mounted inside the container
  automountServiceAccountToken: true
  containers:
    - name: busybox-container
      image: busybox
      command: ["sh", "-c", "sleep 3600"]
