apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: my-app
    version: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
      version: green
  template:
    metadata:
      labels:
        app: my-app
        # version: green is the new version
        # Not receiving traffic yet — Service selector still points to blue
        version: green
    spec:
      containers:
        - name: nginx-container
          image: nginx:1.21
          ports:
            - containerPort: 80
