apiVersion: v1
kind: Pod
metadata:
  name: my-broken-pod-2
  labels:
    app: broken-app
spec:
  containers:
    - name: app-container
      image: busybox
      # This command simulates an app that crashes because
      # a required environment variable is not set
      command: ["sh", "-c", "if [ -z $DATABASE_URL ]; then echo 'DATABASE_URL environment variable not set'; exit 1; fi"]
  restartPolicy: Always
