apiVersion: v1
kind: Pod
metadata:
  name: my-broken-pod-3
  labels:
    app: broken-app
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        requests:
          # Requesting 100Gi memory — more than any node has
          # Will cause Pod to stay in Pending state forever
          memory: "100Gi"
          cpu: "1"
