apiVersion: v1
kind: ResourceQuota
metadata:
  name: my-quota
spec:
  hard:
    # Total CPU allowed across all Pods in this namespace
    requests.cpu: "1"
    limits.cpu: "2"
    # Total memory allowed across all Pods in this namespace
    requests.memory: "512Mi"
    limits.memory: "1Gi"
    # Maximum number of Pods allowed in this namespace
    pods: "5"
